name: 'Setup Playwright'
description: 'Install Playwright browsers and dependencies'

runs:
  using: 'composite'
  steps:
    - name: Install Playwright browsers
      shell: bash
      run: pnpm exec playwright install --with-deps
